export const WorkReports = [
  {
    id: 1,
    date: "2023-04-06",
    "workerName-0": "Fritz",
    "workerFrom-0": "08:00",
    "workerTo-0": "17:00",
    "workerPause-0": "00:30",
    customerFirstName: "Andreas",
    customerSecondName: "Bergstein",
    customerAddress: "Hamburg",
    "materials-0": "Erde",
    "materials-0-amount": "1",
    "materials-0-t": "t",
    "materials-1": "Unterbau",
    "materials-1-amount": "2",
    "materials-1-m3": "m3",
    "materials-2": "Lava",
    "materials-2-amount": "3",
    "materials-2-t": "t",
    "machinesAndDevices-0": "Laubbläser",
    "machinesAndDevices-1": "Kompaktbagger",
    "disposal-0": "Grüngut",
    "disposal-0-amount": "2",
    "disposal-0-m3": "m3",
    "disposal-1": "Oberboden",
    "disposal-1-amount": "1",
    "disposal-1-t": "t",
    "plant-0": "Apfelbaum",
    "plant-0-amount": "20",
    "plant-1": "Kirsche",
    "plant-1-amount": "1",
  },
];
